### ISSUE TITLE
[Android] Select app as shortcut

### ISSUE THREAD

**Issue by VVill-ga** [appstome/timetome-app#1]
Not sure of the complexity of this feature, but I'd like to use the shortcuts feature which lets you open a website  after setting a new task, to open a specific app instead.

This StackOverflow thread may help for getting started: https://stackoverflow.com/questions/2695746/how-to-get-a-list-of-installed-android-applications-and-pick-one-to-run

**Comment by appstome** [comment]
Wow! Alright, the first issue for my app :)

It's amazing how customers find very specific features without any documentation.

Okay, this feature is already in my backlog, as well as ~200 others :). So I'm going to start that first.

I synchronize releases with lunar cycles, so I hope to release this in the first lunar quarter (January 19).

**Comment by appstome** [comment]
@VVill-ga https://github.com/appstome/timetome-app/releases/tag/2023.01.16.460

Done! For now you can download the apk from the release page. Soon it will be available on Google Play and F-Droid.

Please check it out and leave feedback.

**Comment by VVill-ga** [comment]
Perfect, thank you! It works great! There's a bunch of system call-y looking things that come up in addition to the apps, but I'm always for extra functionality. 

Maybe at some point it can be sorted by things that are actual apps and things that aren't, and maybe add a little icons next to apps that have them for easier recognition, but at this point the feature works great and I'd consider it done. Thank you!

**Comment by appstome** [comment]
> Maybe at some point it can be sorted by things that are actual apps and things that aren't, and maybe add a little icons 

I've already added this + search bar to the back log.
