### ISSUE TITLE
Suggestion: display planned time in place of the clock

### ISSUE THREAD

**Issue by virtos** [appstome/timetome-app#12]
It would be nice to see how much time is planned by task items in the folder. The logical place could be in the bottom of the screen in place of the system clock.   
For example, I planned to study math for 4 hours, have a couple of meals for 40 minutes each, and have several other tasks of various lengths. Did I plan all of available time? Can I add more tasks? Will I fail because I planned too much? Displaying total planned time would answer these questions.  
Displaying spent time would also be very useful.

**Comment by appstome** [comment]
For such tasks I use goals https://f-droid.org/repo/me.timeto.app/en-US/phoneScreenshots/4.jpg

**Comment by virtos** [comment]
It is not clear how to achieve this. Example: I have 17 tasks for today of different duration with different categories. What do I have to do to find out how much time I allocated?

**Comment by appstome** [comment]
I'm not sure I understand you well, but you can set a goal for each activity.
