### ISSUE TITLE
need an alarm system

### ISSUE THREAD

**Issue by jewel109** [appstome/timetome-app#14]
After finishing a job the app will show a notification and also alarm

**Comment by appstome** [comment]
I've thought about this before. For example, it could be useful for a "sleeping task". Please let me know what kind of tasks you need this feature for.

**Comment by appstome** [comment]
The current version alarms when the timer expires. You can set custom sound. That doesn't work for you?

**Comment by jewel109** [comment]
Sorry I found out . But it's not an alarm but notification so it rings for less than 5 seconds . I didn't get it.

**Comment by appstome** [comment]
In my experience trying to make notifications more intense just forces us to ignore them more.

Moreover, it is almost impossible to make alarm clocks reliable on Android. So at this point, I don't plan to implement it.

If you really need it, please fork the project, I'll help you if there are any problems.
