### ISSUE TITLE
summary view crashes when activity starts at 00:00

### ISSUE THREAD

**Issue by Boo1098** [appstome/timetome-app#21]
I found that when I go to the activity view and select a date range that includes a day that has an activity that starts at 00:00 the app will crash as soon as that day is displayed. If the day happens to be off the screen when the date range is selected, it won't crash until you scroll over to the day.

I was able to reproduce by going into history and adding an activity with a start time of 00:00. After deleting the activity from the history there is no more crashing.

This is on V2024.02.24.483-fdroid

![Screenshot_20240316-225955 (1)](https://github.com/appstome/timetome-app/assets/7719705/e6eb38e3-7302-423f-9371-2305e4ec13c4)

Thanks!

**Comment by appstome** [comment]
Thanks for the issue!

I am sorry for not answering. This will be fixed in the next release.

**Comment by dextertd** [comment]
Just want to add for the sake of being comprehensive that this also happens when selecting the date range in the pie chart view.

**Comment by appstome** [comment]
Okay. The new release with 385 commits is available in all stores. Please let me know if this bug is still occurring.

**Comment by dextertd** [comment]
Works perfectly for me now, thank you!

-------- Original Message --------
