### ISSUE TITLE
Regarding Checklists in Repeated Tasks

### ISSUE THREAD

**Issue by ShorterTuxedo** [appstome/timetome-app#22]
Hello,

Firstly, I have no words and I cannot thank you enough for producing this amazing app.  I've installed it on my Xiaomi Smart Clock to act as a physical pomodoro timer.

I just have a question - I created a repeating task "RT 1", there is an option which specifies an activity. I created an activity "Activity 1", while specifying a checklist "Checklist 1" for that activity. However, when I started the timer for the "RT 1“, I coudn't see "Checklist 1". May I please ask if this is a correct way to use checklists in repeating tasks, or is this not a supported feature yet?

**Comment by ShorterTuxedo** [comment]
Also, if it's convenient to do so, is adding documentation for the app possible?

**Comment by appstome** [comment]
Hi,

I'm not sure I understood you right. If you want to show a checklist each time you run an activity, you need to specify a checklist for that activity, not for a repeating task.

If you set a checklist for a repeating task, the checklist will be shown when you start that task from the task list.

I'am working on the readme. The first version is here https://github.com/appstome/timetome-app?tab=readme-ov-file#how-to-use-the-app it might help you.

Anyway, if anything is unclear, I'd be happy to help.

**Comment by ShorterTuxedo** [comment]
<img width="253" alt="image" src="https://github.com/appstome/timetome-app/assets/49613009/e0b59d6c-931b-4835-91d2-fda978d5459b">
Thank you for your swift reply.
I'm sorry for not making  my words clear, what i mean was that when I start Repeating task 1, the checklist doesn't start.

**Comment by appstome** [comment]
At the moment, if you want to run a checklist for a repeating task, it must be specified for that repeating task, not for the activity.

Sometimes it's not convenient, but it gives you a lot of flexibility. It's not a problem for me, because I don't often create repeating tasks. Is it a problem for you?

**Comment by ShorterTuxedo** [comment]
Thank you for your swift clarification.  

Still, an amazing app! I thank you massively!

**Comment by appstome** [comment]
I'm glad the app I designed 100% for my personal use has been useful to a lot of people. :)
