### ISSUE TITLE
Option to add activity data to the history.

### ISSUE THREAD

**Issue by ConEstArthur** [appstome/timetome-app#24]
Is there any convinient way to add activity data to the history in cases when I forget to press the timer in the app ?

For an example -  I had dinner at 8pm. Now at 10 I realise I forgot to start timer for the aforementioned task.
How do I add it ? 
and ofcourse time which is not logged can be counted under "other" activity.

**Comment by appstome** [comment]
Yes, it is possible. Open history, tap the pencil icon at the bottom left, select the task you need and change the time by swiping up/down.

**Comment by ConEstArthur** [comment]
> Yes, it is possible. Open history, tap the pencil icon at the bottom left, select the task you need and change the time by swiping up/down.

My bad.
Thanks a lot for your hard work.
Easily the best productivity app out there.
