### ISSUE TITLE
Add iPad layout

### ISSUE THREAD

**Issue by mariobrostech** [appstome/timetome-app#6]
Hi,

I already use timeto on my Android device, so I decided to check it out on my iPad. However, it appears as if the app doesn’t have a iPad-native layout, so the UI appears as a tiny portion of the screen with massive pillar boxes surrounding it.

Would you consider implementing an iPad layout for people that own iPads and wish to use the extra screen real-estate that this affords them in timeto?

Thanks in advance!

**Comment by appstome** [comment]
Hi!

Yes, this is already in my backlog, but I can't give any deadlines.

**Comment by mariobrostech** [comment]
Great, glad to hear that this is on the roadmap! I’ll leave this issue open so you can close it once this feature makes it into the app.

**Comment by mariobrostech** [comment]
Okay, no worries!

I'll note that leaving longer-term issues open usually reduces the possibility for duplicate issues being made, since people generally check for existing issues before opening a new one, and GitHub only shows open issues with searches by default.

In any case, I'll close this issue for now, since that seems to be what you prefer. Please send an update here once this has been implemented or is ready for testing in a pre-release form! I'd be happy to help you test this, if you'd like.
