### ISSUE TITLE
Automatically switch tasks

### ISSUE THREAD

**Issue by jvadair** [appstome/timetome-app#7]
Hello,

I cannot seem to find a way to automatically switch tasks based on time or other conditions. Am I naive? Is there a way to do this that I can't find? If not, this would be a great feature to have so that one does not have to grab their phone first thing in the morning to change from a "sleeping" task or skew the data.

I only recently installed the app, but it looks like a very neat and useful way to track time habits! I appreciate the work you've put into the app.

**Comment by appstome** [comment]
Hi,

I thought about this feature, but decided it was the wrong way. It will show not real information about how long everything takes, but how we would like it to take.

**Comment by jvadair** [comment]
Alright, that's understandable. Perhaps a better solution would be to add the ability to edit the timeline later if you forget to switch the activity.

**Comment by appstome** [comment]
It's already here. The button on the "History" screen is in the bottom left corner.

**Comment by jvadair** [comment]
Oh, my bad. I looked there earlier but couldn't seem to find it. I'll close this issue.
