### ISSUE TITLE
App should not hide the status bar

### ISSUE THREAD

**Issue by virtos** [appstome/timetome-app#9]
When the app is open android status bar is hidden. Arguably this should not be the default behavior considering the app is supposed to run all the time.

**Comment by appstome** [comment]
The battery level and time are always displayed at the bottom. About notifications, I believe they should not distract from the task you are currently focused on.

**Comment by virtos** [comment]
It seems the app is confused about it's function as of now. Like focus building apps it hides notifications and distractions, but then it is supposed to run all the time like a time tracking app. Limiting notifications 24/7 is strange. Making users switch away from time tracking app is also strange.

**Comment by appstome** [comment]
We're all different. We have different lifestyles and work processes. What works for you may not work for others. If this method doesn't suit you, please fork the project and redesign it for yourself. That's why I put the code in open source.

**Comment by appstome** [comment]
One more point: iOS, by its system design, never shows notifications in the status bar. But billions of people use it well.
